import "./globals.css";
import type { Metadata } from "next";
// import Navbar from "@/components/custom/Navbar";
import { Geist, Geist_Mono } from "next/font/google";
// import Sidepanel from "@/components/custom/Sidepanel";
import { ThemeProvider } from "@/components/theme/theme-provider";
import LazyAppProviders from "@/components/custom/react-pdf/LazyAppProviders";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <LazyAppProviders licenseKey={process.env.NEXT_PUBLIC_REACT_PDF_KEY || ""}>
                        <div className="flex">
                            {/* <div> <Sidepanel /> <Navbar /> </div> */}
                            <div className="flex flex-col w-full">
                                {children}
                            </div>
                        </div>
                    </LazyAppProviders>
                </ThemeProvider>
            </body>
        </html>
    );
}
