name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:       # manual trigger

jobs:
  sync:
    # Run only if NOT in the original repo
    if: github.repository != 'klrab3490/DocuSignLoan'
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          owner: rahul-genzoic
          base: main
          head: main